import React from 'react'
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
  } from "@/components/ui/accordion"
import Header from '../dashboard/_components/Header'
import Footer from '../footer'

function page() {
  return (
    <>
    <Header></Header>
    <div className='mt-12 relative flex flex-col items-center justify-center gap-12'>
        <h1 className='text-center font-black text-4xl'>Frequently Asked Questions (FAQs)</h1>
        <div className='w-2/4 py-3'>
            <Accordion type="single" collapsible>
            <AccordionItem value="item-1">
                <AccordionTrigger className='text-xl'>What is VirtuoAI and how does it work?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                VirtuoAI is an AI-powered interview platform designed to help users prepare for job interviews. By inputting the job position, required skills, and years of experience, our AI generates personalized interview questions. This helps users practice and receive feedback to improve their interview performance.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
                <AccordionTrigger className='text-xl'>What kind of interview questions can I expect?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                The questions generated by VirtuoAI are tailored to the job position and skills you provide. They cover a range of topics including technical skills, problem-solving abilities, behavioral questions, and situational scenarios relevant to the job role.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-3">
                <AccordionTrigger className='text-xl'>How does VirtuoAI provide feedback on my answers?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                After you complete the interview, VirtuoAI analyzes your responses and provides detailed feedback, including correct answers and suggestions for improvement. This helps you understand your strengths and areas where you need to improve.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-4">
                <AccordionTrigger className='text-xl'>Can I use VirtuoAI for multiple job positions?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                Absolutely! You can use VirtuoAI to generate interviews for different job positions, skills, and experience levels. This allows you to practice and prepare for a variety of job roles and improve your interview skills across different fields.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-5">
                <AccordionTrigger className='text-xl'>How do I start an interview on VirtuoAI?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                To start an interview, simply sign in to your VirtuoAI account, provide the job position, relevant skills, and years of experience. Our AI will then generate a customized set of interview questions for you to answer.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-6">
                <AccordionTrigger className='text-xl'>Is there a limit to the number of interviews I can take?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                There is no limit to the number of interviews you can take on VirtuoAI. You can generate and practice as many interviews as you need to feel confident and prepared for your real job interviews.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-7">
                <AccordionTrigger className='text-xl'>How is VirtuoAI different from other interview preparation tools?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                VirtuoAI stands out by providing AI-generated, personalized interview questions tailored specifically to the job position, skills, and experience you input. Additionally, our platform offers detailed feedback and suggestions for improvement, making it a comprehensive and adaptive tool for interview preparation.
                </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-8">
                <AccordionTrigger className='text-xl'>Can I save my interview sessions and review them later?</AccordionTrigger>
                <AccordionContent className='text-lg text-gray-600'>
                Yes, VirtuoAI allows you to save your interview sessions. You can review your answers, feedback, and suggestions for improvement at any time, which helps you track your progress and prepare more effectively for future interviews.
                </AccordionContent>
            </AccordionItem>
            </Accordion>
        </div>
    </div>
    <Footer></Footer>
    </>
  )
}

export default page
